spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234
    hikari:
      auto-commit: true
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    org:
      mybatis: ERROR
      mybatis.spring: ERROR
    com:
      haiyin: ERROR
    root: debug


